debug: true
pprof: false
dev: true

log:
  log-level: trace # trace # 输出到console的日志
  # store-level: info
  report-level: debug # 上报到日志系统的日志等级
  to-console: true
  filename: ""
  max-size: 20
  max-backups: 100
  max-age: 60
  local-time: false
  compress: true
